name: "tokenizer"
backend: "python"
max_batch_size : 32

input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 1
  }
]

version_policy{all {} }
